name: mahfazti_mobile
description: "Mahfazti - Personal Finance Mobile Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Network
  dio: ^5.11.0

  # Storage
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.3.3

  # Navigation
  go_router: ^15.1.2

  # State Management
  flutter_riverpod: ^2.6.1

  # Charts
  fl_chart: ^0.71.0

  # Icons
  lucide_icons: ^0.257.0

  # Date & Number Formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # App Icon Generator
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  # =========================================================
  # ASSETS
  # =========================================================

  assets:
    - assets/icons/mahfazti_icon.png

# =============================================================
# FLUTTER LAUNCHER ICONS
# =============================================================

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/mahfazti_icon.png"
  min_sdk_android: 21